version: '3'

services:
  app:
    build: .
    depends_on:
    - db
    ports:
    - "127.0.0.1:8080:8080"

  db:
    image: "mysql"
    ports:
    - "127.0.0.1:1234:1234"
    environment:
      MYSQL_DATABASE: 'tanuki'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'

  db-web:
    image: "taivokasper/omnidb"
    depends_on:
    - db
    ports:
    - "127.0.0.1:25482:80"
