version: '3'

services:
  app:
    build: .
    depends_on:
    - db
    ports:
    - '127.0.0.1:1000:1000'
    environment:
      POSTGRES_HOST: 'db'
      POSTGRES_DB: 'tanuki'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: 'admin'

  db:
    image: 'postgres'
    ports:
    - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_HOST: 'db'
      POSTGRES_DB: 'tanuki'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: 'admin'

  db-admin:
    image: 'adminer'
    depends_on:
    - db
    - app
    ports:
      - 8080:8080