version: '3'

services:
  tanuki-app:
    build: .
    depends_on:
    - tanuki-db
    ports:
    - '127.0.0.1:8080:8080'
    environment:
      POSTGRES_HOST: 'db'
      POSTGRES_DB: 'tanuki'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: 'admin'

  tanuki-db:
    image: 'postgres'
    ports:
    - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_HOST: 'db'
      POSTGRES_DB: 'tanuki'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: 'admin'

  tanuki-db-admin:
    image: 'adminer'
    ports:
      - 8079:8079